### ISSUE TITLE
About GCN

### ISSUE THREAD

**Issue by ZijunDeng** [ycszen/pytorch-ss#6]
Hi 师兄 ^_^, I have some questions, some of which may not be related to your code directly. Look forward to your answers. 

1. The GCN paper shows that the larger kernel size of GCN is, the better segmentation result is. I see your default kernel size is 7 (not the largest one 15 in the paper). What is your consideration?
2. The paper seems not to do ablation experiment on the kernel size setting of GCN in intermediate layers of resnet. In intermediate layers, the size of feature map is larger than 16*16, do you have any idea about the kernel size setting in intermediate layers?
3. How about combining GCN with dilation?

Thanks for your sharing of the nice code!

**Comment by ycszen** [comment]
Sorry, I reply too late. 
1. The kernel size is also 7 in the paper. I have asked the author, he gives the answer that lager kernel size give just a little increasing performance but more memory cost.
2. The intermediate layers' feature maps is larger because the dilation. It is same as the pspnet's basemodel.
3. The large kernel is not equal to dilation. Large Kernel has more parameters, but maybe better performance. Dilation is mainly used for enlarging receptive field.

**Comment by ZijunDeng** [comment]
Thanks! Valuable information!

**Comment by ycszen** [comment]
No thanks.

**Comment by huangh12** [comment]
@ZijunDeng  What do you mean saying "The paper seems not to do ablation experiment on the kernel size setting of GCN in intermediate layers of resnet". In section 4.1.2 of the original paper, the authors replaced the bottleneck structure in ResNet with the GCN module and found no imporvement in classification task. Isn't this a ablation study? :)

**Comment by ZijunDeng** [comment]
I means that the paper doesn't tell the details about GCN's kernel size setting for res-2, res-3 and res-4 as you can see in figure 2A.
